# Generated by Django 3.2.21 on 2024-02-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('paymentstatus', models.CharField(max_length=200)),
                ('note', models.CharField(default=1, max_length=200)),
                ('completionstatus', models.CharField(default=1, max_length=200)),
                ('status', models.CharField(default=1, max_length=200)),
                ('amount', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.login')),
            ],
        ),
        migrations.CreateModel(
            name='serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('contactnumber', models.BigIntegerField()),
                ('lattitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.login')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('SERVICE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.service')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('BOOKING', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.booking')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.user')),
            ],
        ),
        migrations.CreateModel(
            name='ownservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default=1, max_length=200)),
                ('SERVICE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.service')),
                ('SERVICEPROVIDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('reply', models.CharField(default=1, max_length=200)),
                ('replydate', models.CharField(default=1, max_length=200)),
                ('SERVICEPROVIDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.serviceprovider')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.user')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='SERVICE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.user'),
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('IFSC_code', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.login')),
            ],
        ),
    ]
