# Generated by Django 3.2.21 on 2024-02-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VECHI_CO_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='SERVICE',
        ),
        migrations.AddField(
            model_name='booking',
            name='OWNSERVICE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VECHI_CO_APP.ownservice'),
        ),
    ]
